name: camera_android
description: Android implementation of the camera plugin.
repository: https://github.com/jaykshirsagar05/plugins/tree/main/packages/camera/camera_android
version: 0.10.4
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: camera
    platforms:
      android:
        package: io.flutter.plugins.camera
        pluginClass: CameraPlugin
        dartPluginClass: AndroidCamera

dependencies:
  camera_platform_interface: ^2.3.1
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.2
  stream_transform: ^2.0.0

dev_dependencies:
  async: ^2.5.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
